project_name: m3u8app
env_files:
  github_token: /home/m3u8/.goreleaser/github_token

before:
  hooks:
    - go mod download

builds:
  - # Build macOS, Linux and Windows versions
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

# .goreleaser.yml
brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: create-go-app
      name: homebrew-cli

    # Template for the url which is determined by the given Token (github or gitlab)
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_template: "https://github.com/temp25/m3u8/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: temp25
      email: gowtham25alaguraj@outlook.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    # folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    # caveats: "Create a new project via interactive console UI into current folder by using `cgapp create` command."

    # Your app's homepage.
    # Default is empty.
    # homepage: "https://create-go.app/"

    # Your app's description.
    # Default is empty.
    description: "A powerful CLI for the Create Go App project. Create a new production-ready project with backend, frontend and deploy automation by running one CLI command!"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOS.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"
