project_name: m3u8app
env_files:
  github_token: /home/m3u8/.goreleaser/github_token

before:
  hooks:
    - go mod download

builds:
  - # Build macOS, Linux and Windows versions
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
#    targets:
#      - linux_amd64
#      - darwin_amd64
#      - darwin_arm64
#      - windows_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOS.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"
